name: Deploy Staging

on:
  create:
    branches:
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying to staging..."
